### ISSUE TITLE
Add possibility to deactivate or activate redirect with button

### ISSUE THREAD

**Issue by singlespeedfahrer** [SimonBrazell/nitter-redirect#1]
nitter.net seems to be overloaded quite often and is then not reachable. Then I have to deactivate the extension to switch to twitter.com. It would be easier if I can deactivate only the redirect temporary.

**Comment by SimonBrazell** [comment]
Also added this to the latest release (v1.1.0)! Let me know what you think.

**Comment by SimonBrazell** [comment]
![Screen Shot 2019-10-14 at 4 18 28 pm](https://user-images.githubusercontent.com/16571951/66730561-47e5d980-ee9e-11e9-9045-758913b29620.png)
The extension now includes a popup menu with the options you wanted :-)
