### ISSUE TITLE
Add possibility to add another nitter instance

### ISSUE THREAD

**Issue by singlespeedfahrer** [SimonBrazell/nitter-redirect#2]
nitter.net ist quite often overloaded and then not reachable. It would be good to add an alternative nitter instance as redirect in preferences.

**Comment by SimonBrazell** [comment]
Hello, sorry not sure why I didn't get notified of this, this is something I added to the latest release (v1.1.0), should be live on both Firefox and the Chrome Web stores now.

**Comment by SimonBrazell** [comment]
![Screen Shot 2019-10-14 at 4 18 28 pm](https://user-images.githubusercontent.com/16571951/66730667-e70ad100-ee9e-11e9-98c3-8b3244c4e271.png)
