### ISSUE TITLE
Problem with url which ends with 'tweets'

### ISSUE THREAD

**Issue by frodon1** [SimonBrazell/nitter-redirect#5]
Using a fresh install of the Mozilla Plugin, the redirect of a twitter address ending with `/tweets` fails.
When browsing Twitter with no redirection, the `/tweets` suffix is automatically stripped.

Ex: https://twitter.com/raymondh/tweets

**Comment by SimonBrazell** [comment]
Hi @frodon1 thanks for reporting this, should be fixed now in v1.1.5. 

Cheers!

**Comment by frodon1** [comment]
Thanks for the fix, it works fine!
