### ISSUE TITLE
Req: XPI-file: Non-cryptic name

### ISSUE THREAD

**Issue by Jonta** [SimonBrazell/nitter-redirect#7]
Right now, going to `~/.mozilla/firefox/[profile-ID]/extensions/`, this extension is identified by an opaque hex-string

An example of an extension that has a clear name, is HTTPS Everywhere: https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/

=)

**Comment by SimonBrazell** [comment]
Hmm yeah I see what you mean, not sure I can change this now that it's done however? This was the first extension I've made, I just accepted the suggested ID at the time of submission...

**Comment by SimonBrazell** [comment]
Confirmed I cannot change this now that its set, sorry.
