### ISSUE TITLE
Instagram->Bibliogram, YouTube->Invidious support?

### ISSUE THREAD

**Issue by ericlathrop** [SimonBrazell/nitter-redirect#8]
[Bibliogram](https://bibliogram.art/) does a similar thing as Nitter, but for Instagram.
[Invidious](https://invidious.snopyta.org/) does a similar thing as Nitter, but for YouTube.
There's an Android app called [UntrackMe](https://framagit.org/tom79/nitterizeme) that supports all three.

How do you feel about supporting these services with this extension?
If you would approve of supporting these services, would you want to code it yourself, or would you accept PRs for it?

**Comment by SimonBrazell** [comment]
Hi @ericlathrop have you had a look at my other extension [Privacy Redirect](https://github.com/SimonBrazell/privacy-redirect)? It does just what you're after I think.

**Comment by ericlathrop** [comment]
Ah, cool! Thanks!
